[package]
name = "mould-nfd"
version = "0.0.6"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]

[dependencies]
mould = "0.0.17"
nfd = { git = "https://github.com/saurvs/nfd-rs" }
permission = "0.1.0"
