[package]
name = "mould-nfd"
version = "0.0.2"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]

[dependencies]
mould = { path = "../mould" }
#nfd = { path = "../nfd-rs" }
nfd = { git = "https://github.com/saurvs/nfd-rs" }
